version: '3.8'


services:
  db:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./.env
  web:
    depends_on:
      - db
    build:
      context: ../app/
      dockerfile: Dockerfile
    volumes: 
      - static_value:/app/static/
    restart: always
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "80:80"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/static/
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - web


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    depends_on:
      - db

  esloader:
    depends_on:
      - elasticsearch
    build:
      context: ../01_etl/
      dockerfile: Dockerfile
    env_file:
      - ./.env

volumes:
  static_value:
  pgdata:
  elasticsearch-data: